[platformio]
default_envs = transmitter, receiver

[env]
build_flags =
    -std=c11
    -Wall
    -Wextra
    -Isrc/common

[env:transmitter]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
framework = noneos-sdk
board = genericCH32V003F4P6
upload_protocol = wch-link
build_flags =
    ${env.build_flags}
    -D TARGET_TRANSMITTER
build_src_filter =
    +<common/>
    +<transmitter/>

[env:receiver]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
framework = noneos-sdk
board = genericCH32V003F4P6
upload_protocol = wch-link
build_flags =
    ${env.build_flags}
    -D TARGET_RECEIVER
build_src_filter =
    +<common/>
    +<receiver/>
